name: 'Deploy to Netlify (dev)'

on:
  push:
    branches:
       - dev

jobs:
  deploy-to-netlify:
    name: 'Deploy'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
      - name: Setup node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 17.9.0
      - name: Build and deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@53de32e559b0b3833615b9788c7a090cd2fddb03
        with:
          install_command: "npm ci"
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE2_ID }}
          BUILD_DIRECTORY: "dist"
          NETLIFY_DEPLOY_MESSAGE: "Dev deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
