name: 'Deploy to Netlify (dev)'

on:
  push:
    branches:
       - dev

jobs:
  deploy-to-netlify:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.1
      - name: Build and deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v1.7.2
        with:
          install_command: "npm ci"
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE2_ID }}
          BUILD_DIRECTORY: "dist"
          NETLIFY_DEPLOY_MESSAGE: "Dev deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
