name: 'Deploy to Netlify (dev)'

on:
  push:
    branches:
       - dev

jobs:
  deploy-to-netlify:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
      - name: Setup node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 17.9.0
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@ac1cb16858bada08a9c71a81240a85cfc3f72913
        with:
          publish-dir: dist
          deploy-message: "Dev deploy ${{ github.sha }}"
          enable-commit-comment: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          production-deploy: true
          github-deployment-environment: nightly
          github-deployment-description: 'Nightly deployment on each commit to dev branch'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE2_ID }}
        timeout-minutes: 1
